### ISSUE TITLE
Support for TYPO3 9.5 

### ISSUE THREAD

**Issue by NiklasLazinbee** [w010/w_query2csv#3]
Is there a plan for support of TYPO3 version 9.5?

Beste Regards 
Niklas

**Comment by w010** [comment]
Please try installing ext typo3db_legacy and then force install w_query2csv (ignoring version dependency)
Then tell me if it works or where is a problem.

**Comment by NiklasLazinbee** [comment]
I have now tested the extension with TYPO3 v9, it works for me

**Comment by w010** [comment]
New version 0.5.0 is now released and has valid 9.5 compatibility. It needs ext typo3db_legacy to be installed, but seems to work as expected.
For doctrine-migrated version see the dev_doctrine branch. Let me know if it works correctly. It may need some more tests.

**Comment by w010** [comment]
10.4 - compatible, typo3db_legacy - free version has landed is now merged to master.
It should work in 9 as well, though I didn't test it there.
